#!/bin/bash
# author: flooijdt
# created: 2023/09/23
# modified: 2023/09/23

# description:
# backups the home directory cotents in a .tar file

# usage:
# backup_script

echo "Hello, ${USER^}"
echo "I will now back up your home directory, ${HOME}"

currentdir=$(pwd)

echo "You are running this script from $currentdir.\nTherefore, I will save the backup in $currentdir."

tar -cf "${currentdir}"/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/Downloads/teste/* 2>/dev/null

echo "Backup completed."

exit 0